### ISSUE TITLE
Add @context, alsoKnownAs, controller to DIDDoc

### ISSUE THREAD

**Issue by tdiesler** [sicpa-dlab/didcomm-jvm#73]
* https://www.w3.org/TR/did-core/#also-known-as
* https://www.w3.org/TR/did-core/#did-controller
* https://www.w3.org/TR/did-core/#json-ld

**Comment by victormartinez-work** [comment]
@dkulic  @yvgny Can we check if Thomas recommendations are included in other didcomm libraries, specially didcomm python? Let's duplicate the issue in the other libraries if needed

**Comment by tdiesler** [comment]
@context is critical because its a required attribute and [WaltId](https://walt.id/) (correctly) rejects docs that don't have a @context

> The [JSON-LD Context](https://www.w3.org/TR/json-ld11/#the-context) is either a [string](https://infra.spec.whatwg.org/#string) or a [list](https://infra.spec.whatwg.org/#list) containing any combination of [strings](https://infra.spec.whatwg.org/#string) and/or [ordered maps](https://infra.spec.whatwg.org/#maps).

**Comment by tdiesler** [comment]
PR: https://github.com/sicpa-dlab/didcomm-jvm/pull/77
